const translations = {
  vi: {
    subtitle: "Trình quản lý tác vụ tự động cho <a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a>",
    badge_recommended: "KHUYẾN DÙNG",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Tạo ảnh miễn phí không giới hạn với Imagen 4 / Nano Banana. Bản nâng cấp toàn diện với Nano Banana Pro / Veo tốc độ cao và ổn định.",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "Phiên bản tiện ích mở rộng quen thuộc. Chạy trực tiếp trên trình duyệt Chrome.",
    link_guide: "Hướng dẫn",
    quickstart_title: "Hướng Dẫn Nhanh",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (Văn bản thành Ảnh)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Chọn chế độ "Nano Banana Pro" → Nhập prompt → Thêm vào Hàng đợi → Bắt đầu. Ảnh được tạo hàng loạt.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. Ảnh Tham Chiếu (Ảnh sang Ảnh)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Nhấn "Add" để tải ảnh tham chiếu → Nhấn ảnh để kích hoạt → Nhập prompt → Bắt đầu. Dùng "Assign to Prompts" để gán ảnh khác nhau cho từng prompt.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. Thư Viện & Tải 4K</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Vào tab Gallery → Nhấn "Refresh" để quét ảnh → Chọn ảnh → Chọn độ phân giải (1K/2K/4K) → Tải về.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. Ảnh thành Video</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Dùng định dạng [V1-S1] trong prompt (Cảnh 1, Video 1) để sắp xếp các clip. Ví dụ: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises". Sao chép định dạng này và dùng LLM để tạo prompt của bạn. Trong Gallery, chọn ảnh tốt nhất → "Frame to Video" hoặc "Merge" để thêm vào tác vụ có sẵn (tự động sắp xếp theo bảng chữ cái).</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. Thư Viện Video</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Chuyển sang tab Videos → Refresh để quét → Di chuột để xem trước → Dùng thanh trượt tốc độ (0.5x-6x) → Nhấn đúp để mở toàn màn hình.</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>Hàng Đợi Tải Xuống + Hủy</strong> - Nút hủy để dừng tải xuống giữa hàng đợi, thanh tiến trình với bộ đếm trực tiếp</li><li><span class="tag new">NEW</span> <strong>Tải Xuống Nhận Biết Upscale</strong> - Tải xuống 1080p/4K xử lý từng cái với thời gian chờ, tránh lỗi "Upscaling Failed"</li><li><span class="tag new">NEW</span> <strong>Nút Quét Tất Cả</strong> - Nút "Scan All" phát sáng vàng với tooltip giải thích quét cuộn toàn trang</li><li><span class="tag imp">IMP</span> <strong>Quét Video Nhanh Gấp 3 Lần</strong> - Giảm độ trễ cuộn từ 800ms xuống 350ms mỗi bước</li><li><span class="tag imp">IMP</span> <strong>Xem Trước Video Lazy</strong> - Video tải theo yêu cầu thay vì tất cả cùng lúc, thư viện tải ngay với hơn 100 video</li><li><span class="tag fix">FIX</span> <strong>Lưu Độ Phân Giải</strong> - Độ phân giải tải video lưu qua các phiên, mặc định đổi sang 720p</li><li><span class="tag fix">FIX</span> <strong>Ngôn Ngữ Mặc Định</strong> - Cài đặt mới mặc định là tiếng Anh</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>Quét Toàn Bộ Thư Viện</strong> - Thư viện bây giờ cuộn qua toàn bộ trang Flow để tìm TẤT CẢ ảnh/video, kể cả với hơn 100 mục (vượt qua lazy loading của Flow)</li><li><span class="tag new">NEW</span> <strong>Tải Xuống Theo Vị Trí Cuộn</strong> - Tải xuống 2K/4K tự động cuộn lại vị trí ảnh để chọn độ phân giải</li><li><span class="tag fix">FIX</span> <strong>Thứ Tự Ảnh Tham Chiếu</strong> - Ảnh 1 bây giờ hiển thị đúng ở vị trí quan trọng nhất (bên trái nhất) trong Flow</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>Chọn Prompt Làm Lại</strong> - Nhấn vào bất kỳ tác vụ nào trong Hàng đợi để xem tất cả prompt, chọn cái cụ thể để làm lại</li><li><span class="tag new">NEW</span> <strong>Gộp vào Hàng Đợi Có Sẵn</strong> - Gộp các mục Frame-to-Video vào tác vụ đang chờ thay vì tạo mới</li><li><span class="tag new">NEW</span> <strong>Bật/Tắt Tự Động Bắt Đầu</strong> - Kiểm soát tác vụ tiếp theo tự động bắt đầu hay chờ bắt đầu thủ công</li><li><span class="tag new">NEW</span> <strong>Hướng Dẫn Tương Tác</strong> - Nhấn nút ? để xem hướng dẫn từng bước</li><li><span class="tag fix">FIX</span> <strong>Độ Phân Giải Tự Động Tải Ảnh</strong> - Tự động tải ảnh bây giờ hỗ trợ 2K/4K (trước đây luôn tải 1K)</li><li><span class="tag imp">IMP</span> <strong>Ngôn Ngữ Tagalog</strong> - Đã thêm bản dịch Filipino/Tagalog đầy đủ</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>Ảnh Tham Chiếu Theo Prompt</strong> - Gán ảnh tham chiếu khác nhau cho từng prompt trong lô</li><li><span class="tag imp">IMP</span> <strong>Phần Thu Gọn</strong> - Giao diện sạch hơn với phần Ảnh Tham Chiếu có thể thu gọn</li><li><span class="tag imp">IMP</span> <strong>Sắp Xếp Lại Cài Đặt</strong> - Cài đặt được nhóm với các phần rõ ràng</li><li><span class="tag imp">IMP</span> <strong>Hiệu Suất</strong> - Lưu giảm độc, tải hình lưới, cập nhật DOM hàng loạt</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Chế Độ Nano Banana Pro</strong> - Tạo ảnh từ văn bản đầy đủ với tải xuống 1K/2K/4K</li><li><span class="tag new">NEW</span> <strong>Thư Viện Ảnh</strong> - Quét, chọn và tải ảnh hàng loạt</li><li><span class="tag new">NEW</span> <strong>Ảnh Thành Video</strong> - Gửi ảnh từ thư viện trực tiếp đến hàng đợi video Veo</li><li><span class="tag new">NEW</span> <strong>Thư Viện Video</strong> - Xem trước video, điều khiển tốc độ, tải hàng loạt</li><li><span class="tag new">NEW</span> <strong>Ảnh Tham Chiếu</strong> - Tải lên và quản lý ảnh tham chiếu cho tạo ảnh</li><li><span class="tag new">NEW</span> <strong>Hệ Thống Hàng Đợi</strong> - Hàng đợi nhiều tác vụ với thư mục tải xuống</li><li><span class="tag imp">IMP</span> <strong>8 Ngôn Ngữ</strong> - Tiếng Việt, Anh, Hindi, Thai, Urdu, Bengal, Tây Ban Nha, Filipino</li>',
  },
  en: {
    subtitle: "Automated Task Manager for <a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a>",
    badge_recommended: "RECOMMENDED",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Create unlimited free images with Imagen 4 / Nano Banana. Comprehensive upgrade with Nano Banana Pro / Veo - high speed and stable.",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "Familiar extension version. Runs directly in your Chrome browser.",
    link_guide: "User Guide",
    quickstart_title: "Quick Start Guide",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (Text-to-Image)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Select "Nano Banana Pro" mode → Enter prompts → Add to Queue → Start. Images generate in bulk.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. Reference Images (Image-to-Image)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Click "Add" to upload reference images → Click image(s) to activate → Enter prompts → Start. Use "Assign to Prompts" to assign different refs to different prompts.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. Gallery & 4K Downloads</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Go to Gallery tab → Click "Refresh" to scan images → Click images to select → Choose resolution (1K/2K/4K) → Download Selected.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. Frame to Video</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Use [V1-S1] format in prompts (Scene 1, Video 1) to organize clips. Example: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises". Copy this format and use an LLM to generate your own prompts. In Gallery, select best images → "Frame to Video" or "Merge" to add to existing job (auto-sorted alphabetically).</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. Video Gallery</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Switch to Videos tab → Refresh to scan → Hover to preview → Use speed slider (0.5x-6x) → Double-click to expand fullscreen.</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>Download Queue + Cancel</strong> - Cancel button to stop downloads mid-queue, progress bar with live counter</li><li><span class="tag new">NEW</span> <strong>Upscale-Aware Downloads</strong> - 1080p/4K downloads process one at a time with wait, preventing "Upscaling Failed" errors</li><li><span class="tag new">NEW</span> <strong>Scan All Button</strong> - Golden glowing "Scan All" button with tooltip explaining full-page scroll scan</li><li><span class="tag imp">IMP</span> <strong>3x Faster Video Scan</strong> - Reduced scroll delay from 800ms to 350ms per step</li><li><span class="tag imp">IMP</span> <strong>Lazy Video Previews</strong> - Videos load on-demand instead of all at once, gallery loads instantly with 100+ videos</li><li><span class="tag fix">FIX</span> <strong>Resolution Persistence</strong> - Video download resolution saves across sessions, default changed to 720p</li><li><span class="tag fix">FIX</span> <strong>Default Language</strong> - New installs default to English</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>Full Gallery Scan</strong> - Gallery now scrolls through entire Flow page to find ALL images/videos, even with 100+ items (beats Flow\'s lazy loading)</li><li><span class="tag new">NEW</span> <strong>Scroll-Aware Downloads</strong> - 2K/4K downloads automatically scroll back to the image position for resolution selection</li><li><span class="tag fix">FIX</span> <strong>Reference Image Order</strong> - Image 1 now correctly appears as most important (leftmost) in Flow</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>Selective Prompt Redo</strong> - Click any job in Queue to see all prompts, select specific ones to redo</li><li><span class="tag new">NEW</span> <strong>Merge to Existing Queue</strong> - Merge Frame-to-Video items into an existing pending job instead of creating new ones</li><li><span class="tag new">NEW</span> <strong>Auto-Start Toggle</strong> - Control whether the next job starts automatically or waits for manual start</li><li><span class="tag new">NEW</span> <strong>Interactive Tutorial</strong> - Click the ? button for a guided walkthrough of all features</li><li><span class="tag fix">FIX</span> <strong>Image Auto-Download Resolution</strong> - Auto-download now respects 2K/4K resolution setting (was always downloading 1K)</li><li><span class="tag imp">IMP</span> <strong>Tagalog Language</strong> - Full Filipino/Tagalog translation added</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>Per-Prompt Reference Images</strong> - Assign different reference images to different prompts in a batch</li><li><span class="tag imp">IMP</span> <strong>Collapsible Sections</strong> - Cleaner UI with collapsible Reference Images section</li><li><span class="tag imp">IMP</span> <strong>Settings Reorganized</strong> - Grouped settings with clear sections (Generation, Timing, Interface)</li><li><span class="tag imp">IMP</span> <strong>Performance</strong> - Debounced saves, lazy-load thumbnails, batch DOM updates</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Nano Banana Pro Mode</strong> - Full text-to-image generation with 1K/2K/4K downloads</li><li><span class="tag new">NEW</span> <strong>Image Gallery</strong> - Scan, select, and batch download generated images</li><li><span class="tag new">NEW</span> <strong>Frame to Video</strong> - Send gallery images directly to Veo video queue</li><li><span class="tag new">NEW</span> <strong>Video Gallery</strong> - Preview videos with speed control, batch download</li><li><span class="tag new">NEW</span> <strong>Reference Images</strong> - Upload and manage reference images for image-to-image generation</li><li><span class="tag new">NEW</span> <strong>Queue System</strong> - Multi-job queue with download folders, job management</li><li><span class="tag imp">IMP</span> <strong>8 Languages</strong> - Vietnamese, English, Hindi, Thai, Urdu, Bengali, Spanish, Filipino</li>',
  },
  hi: {
    subtitle: "<a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a> ke liye svachalit karya prabandak",
    badge_recommended: "ANUSHANSIT",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Imagen 4 / Nano Banana ke saath aseeemit muft chhaviyaan banaen. Nano Banana Pro / Veo ke saath vyaapak upgrade.",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "Parichit extension sanskaran. Seedhe aapke Chrome browser mein chalta hai.",
    link_guide: "Upyogkarta Guide",
    quickstart_title: "Tvarit Praarambh Guide",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (Text se Image)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">"Nano Banana Pro" mode chunen → Prompts darj karein → Queue mein jodein → Shuru karein. Bulk mein images banti hain.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. Reference Images (Image se Image)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">"Add" par click karein → Image(s) ko activate karein → Prompts darj karein → Shuru karein.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. Gallery & 4K Downloads</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Gallery tab mein jaayein → "Refresh" karein → Images chunein → Resolution chunein (1K/2K/4K) → Download karein.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. Frame se Video</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Prompts mein [V1-S1] format ka upyog karein (Scene 1, Video 1) clips ko vyavasthit karne ke liye. Udaharan: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises". Is format ko copy karein aur apne prompts banane ke liye LLM ka upyog karein. Gallery mein sabse acchi images chunein → "Frame to Video" ya "Merge" dabayein (swachalit roop se varnamala kram mein).</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. Video Gallery</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Videos tab mein jaayein → Refresh karein → Hover se preview → Speed slider (0.5x-6x) → Double-click se fullscreen.</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>Download Queue + Radd</strong> - Download beech mein rokne ke liye Cancel button, progress bar live counter ke saath</li><li><span class="tag new">NEW</span> <strong>Upscale-Jagruk Downloads</strong> - 1080p/4K downloads ek-ek karke wait ke saath process hote hain, "Upscaling Failed" galtiyon se bachata hai</li><li><span class="tag new">NEW</span> <strong>Scan All Button</strong> - Sunehre chamakdaar "Scan All" button tooltip ke saath jo poore page scroll scan samjhata hai</li><li><span class="tag imp">IMP</span> <strong>3x Tez Video Scan</strong> - Scroll delay 800ms se ghataakar 350ms prati step</li><li><span class="tag imp">IMP</span> <strong>Lazy Video Previews</strong> - Video maang par load hote hain sabhi ek saath nahi, gallery turant load hoti hai 100+ videos ke saath</li><li><span class="tag fix">FIX</span> <strong>Resolution Sthirta</strong> - Video download resolution sessions mein save hota hai, default 720p badla gaya</li><li><span class="tag fix">FIX</span> <strong>Default Bhasha</strong> - Naye installations mein default English hai</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>Poorn Gallery Scan</strong> - Gallery ab poore Flow page ko scroll karke SABHI images/videos dhundhti hai, 100+ items ke saath bhi (Flow ki lazy loading ko harati hai)</li><li><span class="tag new">NEW</span> <strong>Scroll-Jagruk Downloads</strong> - 2K/4K downloads swachalit roop se image ki jagah par wapas scroll karte hain resolution chunne ke liye</li><li><span class="tag fix">FIX</span> <strong>Reference Image Kram</strong> - Image 1 ab sahi tarah se sabse mahatvapoorn (sabse baayein) dikhti hai Flow mein</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>Chuninda Prompt Dobara</strong> - Queue mein kisi bhi job par click karein aur chuninda prompts dobara karein</li><li><span class="tag new">NEW</span> <strong>Maujuda Queue Mein Jodein</strong> - Frame-to-Video items ko maujuda pending job mein milayein</li><li><span class="tag new">NEW</span> <strong>Auto-Start Toggle</strong> - Control karein ki agla job automatic shuru ho ya manual</li><li><span class="tag new">NEW</span> <strong>Interactive Tutorial</strong> - ? button par click karke sabhi features ka guided walkthrough dekhein</li><li><span class="tag fix">FIX</span> <strong>Image Auto-Download Resolution</strong> - Auto-download ab 2K/4K resolution ka samman karta hai</li><li><span class="tag imp">IMP</span> <strong>Tagalog Bhasha</strong> - Poorn Filipino/Tagalog anuvad joda gaya</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>Prompt-wise Reference Images</strong> - Alag-alag prompts ke liye alag reference images assign karein</li><li><span class="tag imp">IMP</span> <strong>Sankuchit Sections</strong> - Reference Images section ko collapse/expand karein</li><li><span class="tag imp">IMP</span> <strong>Settings Punargathit</strong> - Spasht vibhaagon ke saath settings</li><li><span class="tag imp">IMP</span> <strong>Pradarshan</strong> - Debounced saves, lazy-load thumbnails</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Nano Banana Pro Mode</strong> - Van ban se chhavi nirmaan 1K/2K/4K downloads ke saath</li><li><span class="tag new">NEW</span> <strong>Chhavi Gallery</strong> - Chhaviyaan scan, select aur batch download karein</li><li><span class="tag new">NEW</span> <strong>Frame se Video</strong> - Gallery se chhaviyaan seedhe Veo video queue mein bhejein</li><li><span class="tag new">NEW</span> <strong>Video Gallery</strong> - Video preview speed control ke saath, batch download</li><li><span class="tag new">NEW</span> <strong>Reference Images</strong> - Tham chieu chhaviyaan upload aur manage karein</li><li><span class="tag new">NEW</span> <strong>Queue System</strong> - Download folders ke saath multi-job queue</li><li><span class="tag imp">IMP</span> <strong>8 Bhashaen</strong> - Vietnamese, English, Hindi, Thai, Urdu, Bengali, Spanish, Filipino</li>',
  },
  th: {
    subtitle: "ตัวจัดการงานอัตโนมัติสำหรับ <a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a>",
    badge_recommended: "แนะนำ",
    glabs_title: "G-Labs Automation",
    glabs_desc: "สร้างรูปภาพฟรีไม่จำกัดด้วย Imagen 4 / Nano Banana อัปเกรดด้วย Nano Banana Pro / Veo",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "เวอร์ชันส่วนขยายที่คุ้นเคย ทำงานในเบราว์เซอร์ Chrome",
    link_guide: "คู่มือผู้ใช้",
    quickstart_title: "คู่มือเริ่มต้นใช้งาน",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (ข้อความเป็นภาพ)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">เลือกโหมด "Nano Banana Pro" → ป้อน prompts → เพิ่มในคิว → เริ่ม สร้างภาพเป็นชุด</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. ภาพอ้างอิง (ภาพเป็นภาพ)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">คลิก "Add" อัปโหลดภาพอ้างอิง → คลิกภาพเพื่อเปิดใช้ → ป้อน prompts → เริ่ม</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. แกลเลอรี่ & ดาวน์โหลด 4K</strong><p style="margin:4px 0 0 0;color:#9aa0a6">ไปแท็บ Gallery → คลิก "Refresh" → เลือกภาพ → เลือกความละเอียด (1K/2K/4K) → ดาวน์โหลด</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. เฟรมเป็นวิดีโอ</strong><p style="margin:4px 0 0 0;color:#9aa0a6">ใช้รูปแบบ [V1-S1] ในพรอมต์ (ฉาก 1, วิดีโอ 1) เพื่อจัดระเบียบคลิป ตัวอย่าง: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises" คัดลอกรูปแบบนี้และใช้ LLM เพื่อสร้างพรอมต์ของคุณเอง ในแกลเลอรี่ เลือกภาพที่ดีที่สุด → "Frame to Video" หรือ "Merge" เพื่อเพิ่มในงานที่มีอยู่ (เรียงตามตัวอักษรอัตโนมัติ)</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. แกลเลอรี่วิดีโอ</strong><p style="margin:4px 0 0 0;color:#9aa0a6">สลับไปแท็บ Videos → Refresh → เลื่อนเมาส์เพื่อดูตัวอย่าง → ใช้สไลเดอร์ความเร็ว (0.5x-6x)</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>คิวดาวน์โหลด + ยกเลิก</strong> - ปุ่มยกเลิกเพื่อหยุดดาวน์โหลดระหว่างคิว แถบความคืบหน้าพร้อมตัวนับสด</li><li><span class="tag new">NEW</span> <strong>ดาวน์โหลดรองรับ Upscale</strong> - ดาวน์โหลด 1080p/4K ประมวลผลทีละรายการพร้อมรอ ป้องกันข้อผิดพลาด "Upscaling Failed"</li><li><span class="tag new">NEW</span> <strong>ปุ่มสแกนทั้งหมด</strong> - ปุ่ม "Scan All" เรืองแสงสีทองพร้อม tooltip อธิบายการสแกนเลื่อนทั้งหน้า</li><li><span class="tag imp">IMP</span> <strong>สแกนวิดีโอเร็วขึ้น 3 เท่า</strong> - ลดความหน่วงเลื่อนจาก 800ms เหลือ 350ms ต่อขั้นตอน</li><li><span class="tag imp">IMP</span> <strong>ตัวอย่างวิดีโอแบบ Lazy</strong> - วิดีโอโหลดตามต้องการแทนที่จะโหลดทั้งหมดพร้อมกัน แกลเลอรี่โหลดทันทีกับวิดีโอ 100+ รายการ</li><li><span class="tag fix">FIX</span> <strong>บันทึกความละเอียด</strong> - ความละเอียดดาวน์โหลดวิดีโอบันทึกข้ามเซสชัน ค่าเริ่มต้นเปลี่ยนเป็น 720p</li><li><span class="tag fix">FIX</span> <strong>ภาษาเริ่มต้น</strong> - การติดตั้งใหม่ตั้งค่าเริ่มต้นเป็นภาษาอังกฤษ</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>สแกนแกลเลอรี่ทั้งหมด</strong> - แกลเลอรี่จะเลื่อนดูทั้งหน้า Flow เพื่อค้นหาภาพ/วิดีโอทั้งหมด แม้มีมากกว่า 100 รายการ (เอาชนะ lazy loading ของ Flow)</li><li><span class="tag new">NEW</span> <strong>ดาวน์โหลดตามตำแหน่งเลื่อน</strong> - ดาวน์โหลด 2K/4K จะเลื่อนกลับไปยังตำแหน่งภาพโดยอัตโนมัติเพื่อเลือกความละเอียด</li><li><span class="tag fix">FIX</span> <strong>ลำดับภาพอ้างอิง</strong> - ภาพที่ 1 แสดงอย่างถูกต้องในตำแหน่งสำคัญที่สุด (ซ้ายสุด) ใน Flow</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>เลือก Prompt ทำซ้ำ</strong> - คลิกงานใดก็ได้ในคิวเพื่อดูทุก prompt เลือกเฉพาะที่ต้องการทำซ้ำ</li><li><span class="tag new">NEW</span> <strong>รวมเข้าคิวที่มีอยู่</strong> - รวมรายการ Frame-to-Video เข้ากับงานที่รอดำเนินการ</li><li><span class="tag new">NEW</span> <strong>สลับเริ่มอัตโนมัติ</strong> - ควบคุมว่างานถัดไปจะเริ่มอัตโนมัติหรือรอเริ่มด้วยตนเอง</li><li><span class="tag new">NEW</span> <strong>บทเรียนแบบโต้ตอบ</strong> - คลิกปุ่ม ? เพื่อดูคำแนะนำทีละขั้นตอน</li><li><span class="tag fix">FIX</span> <strong>ความละเอียดดาวน์โหลดอัตโนมัติ</strong> - ดาวน์โหลดอัตโนมัติรองรับ 2K/4K แล้ว</li><li><span class="tag imp">IMP</span> <strong>ภาษาตากาล็อก</strong> - เพิ่มการแปลภาษาฟิลิปปินส์/ตากาล็อกครบถ้วน</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>ภาพอ้างอิงตาม Prompt</strong> - กำหนดภาพอ้างอิงต่างกันให้แต่ละ prompt</li><li><span class="tag imp">IMP</span> <strong>ส่วนยุบได้</strong> - UI สะอาดขึ้นด้วยส่วนภาพอ้างอิงที่ยุบได้</li><li><span class="tag imp">IMP</span> <strong>จัดระเบียบการตั้งค่า</strong> - การตั้งค่าจัดกลุ่มชัดเจน</li><li><span class="tag imp">IMP</span> <strong>ประสิทธิภาพ</strong> - Debounced saves, lazy-load thumbnails</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>โหมด Nano Banana Pro</strong> - สร้างภาพจากข้อความพร้อมดาวน์โหลด 1K/2K/4K</li><li><span class="tag new">NEW</span> <strong>แกลเลอรี่ภาพ</strong> - สแกน เลือก และดาวน์โหลดภาพเป็นชุด</li><li><span class="tag new">NEW</span> <strong>เฟรมเป็นวิดีโอ</strong> - ส่งภาพจากแกลเลอรี่ไปยังคิววิดีโอ Veo</li><li><span class="tag new">NEW</span> <strong>แกลเลอรี่วิดีโอ</strong> - ดูตัวอย่างวิดีโอพร้อมควบคุมความเร็ว</li><li><span class="tag new">NEW</span> <strong>ภาพอ้างอิง</strong> - อัปโหลดและจัดการภาพอ้างอิง</li><li><span class="tag new">NEW</span> <strong>ระบบคิว</strong> - คิวหลายงานพร้อมโฟลเดอร์ดาวน์โหลด</li><li><span class="tag imp">IMP</span> <strong>8 ภาษา</strong> - เวียดนาม อังกฤษ ฮินดี ไทย อูรดู เบงกาลี สเปน ฟิลิปปินส์</li>',
  },
  ur: {
    subtitle: "<a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a> کے لیے خودکار ٹاسک مینیجر",
    badge_recommended: "تجویز کردہ",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Imagen 4 / Nano Banana کے ساتھ لامحدود مفت تصاویر بنائیں۔ Nano Banana Pro / Veo کے ساتھ اپ گریڈ۔",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "مانوس ایکسٹینشن ورژن۔ براہ راست آپ کے کروم براؤزر میں چلتا ہے۔",
    link_guide: "صارف گائیڈ",
    quickstart_title: "فوری شروع گائیڈ",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (متن سے تصویر)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">"Nano Banana Pro" موڈ منتخب کریں → پرامپٹ درج کریں → قطار میں شامل کریں → شروع کریں۔</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. حوالہ تصاویر</strong><p style="margin:4px 0 0 0;color:#9aa0a6">"Add" پر کلک کریں → تصاویر فعال کریں → پرامپٹ درج کریں → شروع کریں۔</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. گیلری اور 4K ڈاؤن لوڈ</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Gallery ٹیب میں جائیں → "Refresh" کلک کریں → تصاویر منتخب کریں → ریزولیوشن چنیں → ڈاؤن لوڈ کریں۔</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. فریم سے ویڈیو</strong><p style="margin:4px 0 0 0;color:#9aa0a6">کلپس کو منظم کرنے کے لیے پرامپٹ میں [V1-S1] فارمیٹ استعمال کریں (سین 1، ویڈیو 1)۔ مثال: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises"۔ اس فارمیٹ کو کاپی کریں اور اپنے پرامپٹ بنانے کے لیے LLM استعمال کریں۔ گیلری میں بہترین تصاویر منتخب کریں → "Frame to Video" یا "Merge" دبائیں (خودکار حروف تہجی ترتیب)۔</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. ویڈیو گیلری</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Videos ٹیب میں جائیں → Refresh کریں → ہوور سے پیش نظارہ → رفتار سلائیڈر (0.5x-6x)۔</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>ڈاؤن لوڈ قطار + منسوخ</strong> - قطار کے دوران ڈاؤن لوڈ روکنے کے لیے منسوخ بٹن، لائیو کاؤنٹر کے ساتھ پروگریس بار</li><li><span class="tag new">NEW</span> <strong>Upscale سے آگاہ ڈاؤن لوڈز</strong> - 1080p/4K ڈاؤن لوڈز انتظار کے ساتھ ایک ایک کرکے پروسیس ہوتے ہیں، "Upscaling Failed" غلطیوں سے بچاتا ہے</li><li><span class="tag new">NEW</span> <strong>سب اسکین بٹن</strong> - سنہری چمکتا "Scan All" بٹن ٹول ٹپ کے ساتھ جو پورے صفحے کی اسکرول اسکین بتاتا ہے</li><li><span class="tag imp">IMP</span> <strong>3 گنا تیز ویڈیو اسکین</strong> - اسکرول تاخیر 800ms سے کم ہو کر 350ms فی قدم</li><li><span class="tag imp">IMP</span> <strong>Lazy ویڈیو پریویو</strong> - ویڈیوز طلب پر لوڈ ہوتے ہیں سب ایک ساتھ نہیں، گیلری 100+ ویڈیوز کے ساتھ فوری لوڈ ہوتی ہے</li><li><span class="tag fix">FIX</span> <strong>ریزولیوشن محفوظ</strong> - ویڈیو ڈاؤن لوڈ ریزولیوشن سیشنز میں محفوظ رہتی ہے، ڈیفالٹ 720p میں تبدیل</li><li><span class="tag fix">FIX</span> <strong>ڈیفالٹ زبان</strong> - نئی انسٹالیشنز میں ڈیفالٹ انگریزی ہے</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>مکمل گیلری اسکین</strong> - گیلری اب پورے Flow صفحے کو اسکرول کرکے تمام تصاویر/ویڈیوز تلاش کرتی ہے، 100+ آئٹمز کے ساتھ بھی (Flow کی lazy loading کو شکست دیتا ہے)</li><li><span class="tag new">NEW</span> <strong>اسکرول سے آگاہ ڈاؤن لوڈز</strong> - 2K/4K ڈاؤن لوڈز خودکار طور پر تصویر کی پوزیشن پر واپس اسکرول کرتے ہیں ریزولیوشن منتخب کرنے کے لیے</li><li><span class="tag fix">FIX</span> <strong>حوالہ تصویر ترتیب</strong> - تصویر 1 اب صحیح طور پر سب سے اہم (بائیں طرف) ظاہر ہوتی ہے Flow میں</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>منتخب پرامپٹ دوبارہ</strong> - قطار میں کسی بھی جاب پر کلک کریں، مخصوص پرامپٹ دوبارہ کریں</li><li><span class="tag new">NEW</span> <strong>موجودہ قطار میں ضم</strong> - Frame-to-Video آئٹمز کو موجودہ جاب میں ملائیں</li><li><span class="tag new">NEW</span> <strong>آٹو سٹارٹ ٹوگل</strong> - اگلا جاب خودکار شروع ہو یا دستی</li><li><span class="tag new">NEW</span> <strong>انٹرایکٹو ٹیوٹوریل</strong> - ? بٹن پر کلک کریں تمام خصوصیات کا رہنما ملاحظہ کریں</li><li><span class="tag fix">FIX</span> <strong>تصویر آٹو ڈاؤن لوڈ ریزولیوشن</strong> - آٹو ڈاؤن لوڈ اب 2K/4K ریزولیوشن کی حمایت کرتا ہے</li><li><span class="tag imp">IMP</span> <strong>ٹیگالوگ زبان</strong> - مکمل فلپائنی ترجمہ شامل</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>پرامپٹ کے مطابق حوالہ تصاویر</strong> - مختلف پرامپٹ کے لیے مختلف حوالہ تصاویر</li><li><span class="tag imp">IMP</span> <strong>سکڑنے والے حصے</strong> - صاف UI</li><li><span class="tag imp">IMP</span> <strong>ترتیبات منظم</strong> - واضح حصوں کے ساتھ ترتیبات</li><li><span class="tag imp">IMP</span> <strong>کارکردگی</strong> - بہتر کارکردگی</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Nano Banana Pro موڈ</strong> - 1K/2K/4K ڈاؤن لوڈ کے ساتھ مکمل تصویر بنانا</li><li><span class="tag new">NEW</span> <strong>تصویر گیلری</strong> - تصاویر سکین، منتخب اور بیچ ڈاؤن لوڈ</li><li><span class="tag new">NEW</span> <strong>فریم سے ویڈیو</strong> - گیلری تصاویر Veo ویڈیو قطار میں بھیجیں</li><li><span class="tag new">NEW</span> <strong>ویڈیو گیلری</strong> - رفتار کنٹرول کے ساتھ ویڈیو پیش نظارہ</li><li><span class="tag new">NEW</span> <strong>حوالہ تصاویر</strong> - حوالہ تصاویر اپ لوڈ اور منظم کریں</li><li><span class="tag new">NEW</span> <strong>قطار سسٹم</strong> - ڈاؤن لوڈ فولڈرز کے ساتھ ملٹی جاب قطار</li><li><span class="tag imp">IMP</span> <strong>8 زبانیں</strong> - ویتنامی، انگریزی، ہندی، تھائی، اردو، بنگالی، ہسپانوی، فلپائنی</li>',
  },
  bn: {
    subtitle: "<a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a>-এর জন্য স্বয়ংক্রিয় টাস্ক ম্যানেজার",
    badge_recommended: "প্রস্তাবিত",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Imagen 4 / Nano Banana দিয়ে আনলিমিটেড ফ্রি ছবি তৈরি করুন। Nano Banana Pro / Veo দিয়ে আপগ্রেড।",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "পরিচিত এক্সটেনশন সংস্করণ। সরাসরি আপনার ক্রোম ব্রাউজারে চলে।",
    link_guide: "ব্যবহারকারী নির্দেশিকা",
    quickstart_title: "দ্রুত শুরু গাইড",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (টেক্সট থেকে ইমেজ)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">"Nano Banana Pro" মোড নির্বাচন করুন → প্রম্পট লিখুন → কিউতে যোগ করুন → শুরু করুন।</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. রেফারেন্স ইমেজ</strong><p style="margin:4px 0 0 0;color:#9aa0a6">"Add" ক্লিক করুন → ইমেজ সক্রিয় করুন → প্রম্পট লিখুন → শুরু করুন।</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. গ্যালারি ও 4K ডাউনলোড</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Gallery ট্যাবে যান → "Refresh" ক্লিক করুন → ইমেজ নির্বাচন করুন → রেজোলিউশন বেছে নিন → ডাউনলোড করুন।</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. ফ্রেম থেকে ভিডিও</strong><p style="margin:4px 0 0 0;color:#9aa0a6">ক্লিপ সংগঠিত করতে প্রম্পটে [V1-S1] ফরম্যাট ব্যবহার করুন (সিন 1, ভিডিও 1)। উদাহরণ: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises"। এই ফরম্যাট কপি করুন এবং আপনার নিজের প্রম্পট তৈরি করতে LLM ব্যবহার করুন। গ্যালারিতে সেরা ইমেজ নির্বাচন করুন → "Frame to Video" বা "Merge" ক্লিক করুন (স্বয়ংক্রিয়ভাবে বর্ণানুক্রমে সাজানো)।</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. ভিডিও গ্যালারি</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Videos ট্যাবে যান → Refresh করুন → হোভার করে প্রিভিউ → স্পিড স্লাইডার (0.5x-6x)।</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>ডাউনলোড কিউ + বাতিল</strong> - কিউয়ের মাঝে ডাউনলোড বন্ধ করতে বাতিল বোতাম, লাইভ কাউন্টার সহ প্রগ্রেস বার</li><li><span class="tag new">NEW</span> <strong>Upscale-সচেতন ডাউনলোড</strong> - 1080p/4K ডাউনলোড অপেক্ষা সহ একটি করে প্রসেস হয়, "Upscaling Failed" ত্রুটি প্রতিরোধ করে</li><li><span class="tag new">NEW</span> <strong>সব স্ক্যান বোতাম</strong> - সোনালি উজ্জ্বল "Scan All" বোতাম টুলটিপ সহ যা পুরো পৃষ্ঠা স্ক্রল স্ক্যান ব্যাখ্যা করে</li><li><span class="tag imp">IMP</span> <strong>3 গুণ দ্রুত ভিডিও স্ক্যান</strong> - স্ক্রল বিলম্ব 800ms থেকে 350ms প্রতি ধাপে কমানো হয়েছে</li><li><span class="tag imp">IMP</span> <strong>Lazy ভিডিও প্রিভিউ</strong> - ভিডিও চাহিদা অনুযায়ী লোড হয় সব একসাথে নয়, 100+ ভিডিও সহ গ্যালারি তাৎক্ষণিক লোড হয়</li><li><span class="tag fix">FIX</span> <strong>রেজোলিউশন সংরক্ষণ</strong> - ভিডিও ডাউনলোড রেজোলিউশন সেশন জুড়ে সংরক্ষিত হয়, ডিফল্ট 720p তে পরিবর্তিত</li><li><span class="tag fix">FIX</span> <strong>ডিফল্ট ভাষা</strong> - নতুন ইনস্টলেশনে ডিফল্ট ইংরেজি</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>সম্পূর্ণ গ্যালারি স্ক্যান</strong> - গ্যালারি এখন সমস্ত ইমেজ/ভিডিও খুঁজে পেতে পুরো Flow পৃষ্ঠায় স্ক্রল করে, এমনকি 100+ আইটেম থাকলেও (Flow-এর lazy loading কে হারায়)</li><li><span class="tag new">NEW</span> <strong>স্ক্রল-সচেতন ডাউনলোড</strong> - 2K/4K ডাউনলোড স্বয়ংক্রিয়ভাবে রেজোলিউশন নির্বাচনের জন্য ইমেজের অবস্থানে ফিরে স্ক্রল করে</li><li><span class="tag fix">FIX</span> <strong>রেফারেন্স ইমেজ ক্রম</strong> - ইমেজ 1 এখন সঠিকভাবে সবচেয়ে গুরুত্বপূর্ণ (বামদিকে) প্রদর্শিত হয় Flow-এ</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>নির্বাচিত প্রম্পট পুনরায়</strong> - কিউতে যেকোনো জবে ক্লিক করুন, নির্দিষ্ট প্রম্পট পুনরায় করুন</li><li><span class="tag new">NEW</span> <strong>বিদ্যমান কিউতে মার্জ</strong> - Frame-to-Video আইটেম বিদ্যমান জবে যোগ করুন</li><li><span class="tag new">NEW</span> <strong>অটো-স্টার্ট টগল</strong> - পরবর্তী জব স্বয়ংক্রিয় শুরু হবে কি না নিয়ন্ত্রণ করুন</li><li><span class="tag new">NEW</span> <strong>ইন্টারঅ্যাক্টিভ টিউটোরিয়াল</strong> - ? বোতামে ক্লিক করুন সমস্ত বৈশিষ্ট্যের গাইডেড ওয়াকথ্রু দেখুন</li><li><span class="tag fix">FIX</span> <strong>ইমেজ অটো-ডাউনলোড রেজোলিউশন</strong> - অটো-ডাউনলোড এখন 2K/4K রেজোলিউশন সমর্থন করে</li><li><span class="tag imp">IMP</span> <strong>তাগালোগ ভাষা</strong> - সম্পূর্ণ ফিলিপিনো অনুবাদ যোগ করা হয়েছে</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>প্রম্পট অনুযায়ী রেফারেন্স ইমেজ</strong> - বিভিন্ন প্রম্পটের জন্য বিভিন্ন রেফারেন্স ইমেজ</li><li><span class="tag imp">IMP</span> <strong>সংকোচনযোগ্য সেকশন</strong> - পরিষ্কার UI</li><li><span class="tag imp">IMP</span> <strong>সেটিংস পুনর্গঠিত</strong> - স্পষ্ট বিভাগ সহ সেটিংস</li><li><span class="tag imp">IMP</span> <strong>পারফরম্যান্স</strong> - উন্নত পারফরম্যান্স</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Nano Banana Pro মোড</strong> - 1K/2K/4K ডাউনলোড সহ সম্পূর্ণ ইমেজ তৈরি</li><li><span class="tag new">NEW</span> <strong>ইমেজ গ্যালারি</strong> - ইমেজ স্ক্যান, নির্বাচন এবং ব্যাচ ডাউনলোড</li><li><span class="tag new">NEW</span> <strong>ফ্রেম থেকে ভিডিও</strong> - গ্যালারি ইমেজ সরাসরি Veo ভিডিও কিউতে পাঠান</li><li><span class="tag new">NEW</span> <strong>ভিডিও গ্যালারি</strong> - স্পিড কন্ট্রোল সহ ভিডিও প্রিভিউ</li><li><span class="tag new">NEW</span> <strong>রেফারেন্স ইমেজ</strong> - রেফারেন্স ইমেজ আপলোড ও পরিচালনা</li><li><span class="tag new">NEW</span> <strong>কিউ সিস্টেম</strong> - ডাউনলোড ফোল্ডার সহ মাল্টি-জব কিউ</li><li><span class="tag imp">IMP</span> <strong>8 ভাষা</strong> - ভিয়েতনামী, ইংরেজি, হিন্দি, থাই, উর্দু, বাংলা, স্প্যানিশ, ফিলিপিনো</li>',
  },
  es: {
    subtitle: "Gestor de tareas automatizado para <a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a>",
    badge_recommended: "RECOMENDADO",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Crea imagenes gratuitas ilimitadas con Imagen 4 / Nano Banana. Actualizacion con Nano Banana Pro / Veo.",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "Version familiar de la extension. Se ejecuta en tu navegador Chrome.",
    link_guide: "Guia de usuario",
    quickstart_title: "Guia de Inicio Rapido",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (Texto a Imagen)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Selecciona modo "Nano Banana Pro" → Ingresa prompts → Agregar a Cola → Iniciar. Las imagenes se generan en lote.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. Imagenes de Referencia</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Haz clic en "Add" → Activa imagenes → Ingresa prompts → Iniciar.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. Galeria y Descargas 4K</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Ve a la pestana Gallery → Haz clic en "Refresh" → Selecciona imagenes → Elige resolucion (1K/2K/4K) → Descargar.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. Frame a Video</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Usa el formato [V1-S1] en los prompts (Escena 1, Video 1) para organizar clips. Ejemplo: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises". Copia este formato y usa un LLM para generar tus propios prompts. En la Galeria, selecciona las mejores imagenes → "Frame to Video" o "Merge" para agregar a un trabajo existente (ordenado alfabeticamente).</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. Galeria de Videos</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Cambia a la pestana Videos → Refresh → Vista previa al pasar el mouse → Control de velocidad (0.5x-6x).</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>Cola de Descargas + Cancelar</strong> - Boton de cancelar para detener descargas en medio de la cola, barra de progreso con contador en vivo</li><li><span class="tag new">NEW</span> <strong>Descargas con Upscale</strong> - Las descargas 1080p/4K se procesan una a la vez con espera, evitando errores de "Upscaling Failed"</li><li><span class="tag new">NEW</span> <strong>Boton Escanear Todo</strong> - Boton "Scan All" con brillo dorado y tooltip que explica el escaneo de pagina completa</li><li><span class="tag imp">IMP</span> <strong>Escaneo de Video 3x Mas Rapido</strong> - Retraso de desplazamiento reducido de 800ms a 350ms por paso</li><li><span class="tag imp">IMP</span> <strong>Previsualizacion Lazy de Videos</strong> - Los videos se cargan bajo demanda en vez de todos a la vez, la galeria carga al instante con 100+ videos</li><li><span class="tag fix">FIX</span> <strong>Persistencia de Resolucion</strong> - La resolucion de descarga de video se guarda entre sesiones, predeterminado cambiado a 720p</li><li><span class="tag fix">FIX</span> <strong>Idioma Predeterminado</strong> - Las nuevas instalaciones usan ingles por defecto</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>Escaneo Completo de Galeria</strong> - La galeria ahora recorre toda la pagina de Flow para encontrar TODAS las imagenes/videos, incluso con mas de 100 elementos (supera la carga diferida de Flow)</li><li><span class="tag new">NEW</span> <strong>Descargas con Desplazamiento</strong> - Las descargas 2K/4K se desplazan automaticamente a la posicion de la imagen para seleccionar la resolucion</li><li><span class="tag fix">FIX</span> <strong>Orden de Imagenes de Referencia</strong> - La imagen 1 ahora aparece correctamente como la mas importante (mas a la izquierda) en Flow</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>Rehacer Prompts Selectivos</strong> - Haz clic en cualquier trabajo en la Cola para ver todos los prompts, selecciona los que quieras rehacer</li><li><span class="tag new">NEW</span> <strong>Fusionar en Cola Existente</strong> - Fusiona items de Frame-to-Video en un trabajo pendiente existente</li><li><span class="tag new">NEW</span> <strong>Toggle Auto-Inicio</strong> - Controla si el siguiente trabajo inicia automaticamente o espera inicio manual</li><li><span class="tag new">NEW</span> <strong>Tutorial Interactivo</strong> - Haz clic en el boton ? para un recorrido guiado de todas las funciones</li><li><span class="tag fix">FIX</span> <strong>Resolucion Auto-Descarga</strong> - La descarga automatica ahora respeta la configuracion 2K/4K</li><li><span class="tag imp">IMP</span> <strong>Idioma Tagalo</strong> - Traduccion completa al Filipino/Tagalo agregada</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>Imagenes Ref por Prompt</strong> - Asigna diferentes imagenes de referencia a diferentes prompts</li><li><span class="tag imp">IMP</span> <strong>Secciones Plegables</strong> - UI mas limpia con secciones plegables</li><li><span class="tag imp">IMP</span> <strong>Ajustes Reorganizados</strong> - Ajustes agrupados con secciones claras</li><li><span class="tag imp">IMP</span> <strong>Rendimiento</strong> - Guardado optimizado, thumbnails lazy-load</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Modo Nano Banana Pro</strong> - Generacion completa de imagenes con descargas 1K/2K/4K</li><li><span class="tag new">NEW</span> <strong>Galeria de Imagenes</strong> - Escanear, seleccionar y descargar imagenes en lote</li><li><span class="tag new">NEW</span> <strong>Frame a Video</strong> - Enviar imagenes de galeria a la cola de video Veo</li><li><span class="tag new">NEW</span> <strong>Galeria de Videos</strong> - Vista previa de video con control de velocidad</li><li><span class="tag new">NEW</span> <strong>Imagenes de Referencia</strong> - Subir y gestionar imagenes de referencia</li><li><span class="tag new">NEW</span> <strong>Sistema de Cola</strong> - Cola multi-trabajo con carpetas de descarga</li><li><span class="tag imp">IMP</span> <strong>8 Idiomas</strong> - Vietnamita, Ingles, Hindi, Tailandes, Urdu, Bengali, Espanol, Filipino</li>',
  },
  tl: {
    subtitle: "Automated Task Manager para sa <a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a>",
    badge_recommended: "INIREREKOMENDA",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Lumikha ng walang limitasyong libreng mga larawan gamit ang Imagen 4 / Nano Banana. Komprehensibong upgrade gamit ang Nano Banana Pro / Veo.",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "Pamilyar na extension version. Tumatakbo direkta sa iyong Chrome browser.",
    link_guide: "Gabay sa Paggamit",
    quickstart_title: "Gabay sa Mabilis na Pagsisimula",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (Text papuntang Image)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Piliin ang "Nano Banana Pro" mode → Ilagay ang mga prompt → Idagdag sa Queue → Simulan. Ang mga larawan ay ginagawa nang marami.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. Reference Images (Image papuntang Image)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">I-click ang "Add" para mag-upload ng reference images → I-click ang image(s) para i-activate → Ilagay ang mga prompt → Simulan.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. Gallery at 4K Downloads</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Pumunta sa Gallery tab → I-click ang "Refresh" para mag-scan → Pumili ng mga larawan → Piliin ang resolution (1K/2K/4K) → I-download.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. Frame papuntang Video</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Gamitin ang [V1-S1] format sa mga prompt (Eksena 1, Video 1) para ayusin ang mga clip. Halimbawa: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises". Kopyahin ang format na ito at gumamit ng LLM para gumawa ng sarili mong mga prompt. Sa Gallery, piliin ang pinakamahusay na mga larawan → "Frame to Video" o "Merge" para idagdag sa umiiral na gawain (awtomatikong inayos ayon sa alpabeto).</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. Video Gallery</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Lumipat sa Videos tab → Refresh para mag-scan → Hover para mag-preview → Gamitin ang speed slider (0.5x-6x) → Double-click para fullscreen.</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>Download Queue + Kanselahin</strong> - Cancel button para itigil ang mga download sa gitna ng queue, progress bar na may live counter</li><li><span class="tag new">NEW</span> <strong>Upscale-Aware na Downloads</strong> - Ang 1080p/4K downloads ay pinoproseso nang isa-isa na may paghihintay, pinipigilan ang "Upscaling Failed" na mga error</li><li><span class="tag new">NEW</span> <strong>Scan All Button</strong> - Gintong kumikinang na "Scan All" button na may tooltip na nagpapaliwanag ng full-page scroll scan</li><li><span class="tag imp">IMP</span> <strong>3x Mas Mabilis na Video Scan</strong> - Binawasan ang scroll delay mula 800ms hanggang 350ms bawat hakbang</li><li><span class="tag imp">IMP</span> <strong>Lazy Video Previews</strong> - Ang mga video ay naglo-load on-demand sa halip na lahat nang sabay-sabay, agad na naglo-load ang gallery na may 100+ videos</li><li><span class="tag fix">FIX</span> <strong>Pag-save ng Resolution</strong> - Ang video download resolution ay nase-save sa mga session, default binago sa 720p</li><li><span class="tag fix">FIX</span> <strong>Default na Wika</strong> - Ang mga bagong install ay naka-default sa English</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>Buong Gallery Scan</strong> - Ang gallery ay nag-i-scroll sa buong Flow page para mahanap ang LAHAT ng images/videos, kahit may 100+ items (tinatalob ang lazy loading ng Flow)</li><li><span class="tag new">NEW</span> <strong>Scroll-Aware na Pag-download</strong> - Ang 2K/4K downloads ay awtomatikong bumabalik sa posisyon ng image para sa pagpili ng resolution</li><li><span class="tag fix">FIX</span> <strong>Ayos ng Reference Image</strong> - Ang Image 1 ay tama nang lumalabas bilang pinaka-importante (pinakakaliwang bahagi) sa Flow</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>Piliin ang Prompt na Ulitin</strong> - I-click ang anumang gawain sa Queue para makita lahat ng prompt, pumili ng mga partikular na ulitin</li><li><span class="tag new">NEW</span> <strong>I-merge sa Umiiral na Queue</strong> - I-merge ang mga Frame-to-Video item sa umiiral na pending na gawain</li><li><span class="tag new">NEW</span> <strong>Auto-Start Toggle</strong> - Kontrolin kung ang susunod na gawain ay magsisimula nang awtomatiko o maghihintay ng manual na pagsisimula</li><li><span class="tag new">NEW</span> <strong>Interactive Tutorial</strong> - I-click ang ? button para sa guided walkthrough ng lahat ng features</li><li><span class="tag fix">FIX</span> <strong>Image Auto-Download Resolution</strong> - Ang auto-download ay sumusuporta na sa 2K/4K resolution</li><li><span class="tag imp">IMP</span> <strong>Wikang Tagalog</strong> - Buong salin sa Filipino/Tagalog idinagdag</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>Per-Prompt Reference Images</strong> - Mag-assign ng iba\'t ibang reference images sa iba\'t ibang prompt</li><li><span class="tag imp">IMP</span> <strong>Mga Nako-collapse na Seksyon</strong> - Mas malinis na UI na may nako-collapse na Reference Images</li><li><span class="tag imp">IMP</span> <strong>Inayos ang Mga Setting</strong> - Mga setting na naka-grupo nang malinaw</li><li><span class="tag imp">IMP</span> <strong>Performance</strong> - Debounced saves, lazy-load thumbnails</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Nano Banana Pro Mode</strong> - Kumpletong paglikha ng larawan na may 1K/2K/4K downloads</li><li><span class="tag new">NEW</span> <strong>Image Gallery</strong> - I-scan, pumili, at mag-batch download ng mga larawan</li><li><span class="tag new">NEW</span> <strong>Frame papuntang Video</strong> - Ipadala ang mga larawan ng gallery sa Veo video queue</li><li><span class="tag new">NEW</span> <strong>Video Gallery</strong> - Preview ng video na may speed control, batch download</li><li><span class="tag new">NEW</span> <strong>Reference Images</strong> - Mag-upload at mag-manage ng reference images</li><li><span class="tag new">NEW</span> <strong>Queue System</strong> - Multi-job queue na may download folders</li><li><span class="tag imp">IMP</span> <strong>8 Wika</strong> - Vietnamese, English, Hindi, Thai, Urdu, Bengali, Spanish, Filipino</li>',
  },
  pt: {
    subtitle: "Gerenciador Automático de Tarefas para <a href='https://labs.google/fx/tools/flow' target='_blank' style='color: inherit; text-decoration: underline;'>Flow AI (Veo)</a>",
    badge_recommended: "RECOMENDADO",
    glabs_title: "G-Labs Automation",
    glabs_desc: "Crie imagens gratuitas ilimitadas com Imagen 4 / Nano Banana. Upgrade completo com Nano Banana Pro / Veo - alta velocidade e estável.",
    classic_title: "Version 9.5.0 + Nano Banana Pro",
    classic_desc: "Versão familiar da extensão. Roda diretamente no seu navegador Chrome.",
    link_guide: "Guia do Usuário",
    quickstart_title: "Guia de Início Rápido",
    quickstart_content: '<div style="margin-bottom:12px"><strong style="color:#8ab4f8">1. Nano Banana Pro (Texto para Imagem)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Selecione o modo "Nano Banana Pro" → Digite prompts → Adicione à Fila → Iniciar. Imagens são geradas em lote.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">2. Imagens de Referência (Imagem para Imagem)</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Clique em "Add" para enviar imagens de referência → Clique na(s) imagem(ns) para ativar → Digite prompts → Iniciar.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">3. Galeria & Downloads 4K</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Vá para a aba Gallery → Clique em "Refresh" para escanear → Selecione imagens → Escolha resolução (1K/2K/4K) → Baixar.</p></div><div style="margin-bottom:12px"><strong style="color:#8ab4f8">4. Frame para Vídeo</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Use o formato [V1-S1] nos prompts (Cena 1, Vídeo 1) para organizar clipes. Exemplo: "[V1-S1] Pancakes on a griddle, golden brown ||| Butter melts across surface, steam rises". Copie este formato e use um LLM para gerar seus próprios prompts. Na Galeria, selecione as melhores imagens → "Frame to Video" ou "Merge" para adicionar a um trabalho existente.</p></div><div style="margin-bottom:0"><strong style="color:#8ab4f8">5. Galeria de Vídeos</strong><p style="margin:4px 0 0 0;color:#9aa0a6">Mude para a aba Videos → Refresh para escanear → Passe o mouse para preview → Use o controle de velocidade (0.5x-6x) → Duplo clique para tela cheia.</p></div>',
    changelog_950: '<li><span class="tag new">NEW</span> <strong>Fila de Downloads + Cancelar</strong> - Botão de cancelar para parar downloads no meio da fila, barra de progresso com contador ao vivo</li><li><span class="tag new">NEW</span> <strong>Downloads com Upscale</strong> - Downloads 1080p/4K processam um de cada vez com espera, evitando erros "Upscaling Failed"</li><li><span class="tag new">NEW</span> <strong>Botão Escanear Tudo</strong> - Botão "Scan All" dourado brilhante com tooltip explicando escaneamento de página completa</li><li><span class="tag imp">IMP</span> <strong>Escaneamento de Vídeo 3x Mais Rápido</strong> - Atraso de rolagem reduzido de 800ms para 350ms por passo</li><li><span class="tag imp">IMP</span> <strong>Previews de Vídeo Lazy</strong> - Vídeos carregam sob demanda ao invés de todos de uma vez, galeria carrega instantaneamente com 100+ vídeos</li><li><span class="tag fix">FIX</span> <strong>Persistência de Resolução</strong> - Resolução de download de vídeo salva entre sessões, padrão alterado para 720p</li><li><span class="tag fix">FIX</span> <strong>Idioma Padrão</strong> - Novas instalações padrão para Inglês</li>',
    changelog_940: '<li><span class="tag new">NEW</span> <strong>Escaneamento Completo da Galeria</strong> - Galeria agora rola por toda a página Flow para encontrar TODAS as imagens/vídeos, mesmo com 100+ itens</li><li><span class="tag new">NEW</span> <strong>Downloads com Rolagem</strong> - Downloads 2K/4K rolam automaticamente de volta à posição da imagem para seleção de resolução</li><li><span class="tag fix">FIX</span> <strong>Ordem das Imagens de Referência</strong> - Imagem 1 agora aparece corretamente como mais importante (mais à esquerda) no Flow</li>',
    changelog_930: '<li><span class="tag new">NEW</span> <strong>Refazer Prompt Seletivo</strong> - Clique em qualquer trabalho na Fila para ver todos os prompts, selecione específicos para refazer</li><li><span class="tag new">NEW</span> <strong>Mesclar na Fila Existente</strong> - Mescle itens Frame-to-Video em um trabalho pendente existente</li><li><span class="tag new">NEW</span> <strong>Auto-Start Toggle</strong> - Controle se o próximo trabalho inicia automaticamente ou aguarda início manual</li><li><span class="tag new">NEW</span> <strong>Tutorial Interativo</strong> - Clique no botão ? para um guia de todas as funções</li><li><span class="tag fix">FIX</span> <strong>Resolução de Auto-Download de Imagem</strong> - Auto-download agora respeita configuração de resolução 2K/4K</li><li><span class="tag imp">IMP</span> <strong>Idioma Tagalog</strong> - Tradução completa para Filipino/Tagalog adicionada</li>',
    changelog_920: '<li><span class="tag new">NEW</span> <strong>Imagens de Referência Por-Prompt</strong> - Atribua diferentes imagens de referência a diferentes prompts</li><li><span class="tag imp">IMP</span> <strong>Seções Recolhíveis</strong> - UI mais limpa com seção de Imagens de Referência recolhível</li><li><span class="tag imp">IMP</span> <strong>Configurações Reorganizadas</strong> - Configurações agrupadas com seções claras</li><li><span class="tag imp">IMP</span> <strong>Performance</strong> - Saves com debounce, thumbnails lazy-load</li>',
    changelog_900: '<li><span class="tag new">NEW</span> <strong>Modo Nano Banana Pro</strong> - Geração completa de texto para imagem com downloads 1K/2K/4K</li><li><span class="tag new">NEW</span> <strong>Galeria de Imagens</strong> - Escaneie, selecione e baixe imagens em lote</li><li><span class="tag new">NEW</span> <strong>Frame para Vídeo</strong> - Envie imagens da galeria diretamente para a fila de vídeo Veo</li><li><span class="tag new">NEW</span> <strong>Galeria de Vídeos</strong> - Preview de vídeos com controle de velocidade, download em lote</li><li><span class="tag new">NEW</span> <strong>Imagens de Referência</strong> - Envie e gerencie imagens de referência para geração imagem-para-imagem</li><li><span class="tag new">NEW</span> <strong>Sistema de Fila</strong> - Fila multi-trabalho com pastas de download</li><li><span class="tag imp">IMP</span> <strong>9 Idiomas</strong> - Vietnamita, Inglês, Hindi, Tailandês, Urdu, Bengali, Espanhol, Filipino, Português</li>',
  },
};

function applyLanguage(lang) {
  const langData = translations[lang];
  if (!langData) return;

  document.querySelectorAll("[data-lang-key]").forEach((el) => {
    const key = el.getAttribute("data-lang-key");
    if (langData[key]) {
      el.innerHTML = langData[key];
    }
  });

  const guideLink = document.querySelector('.link-item[href*="github.com"]');
  if (guideLink) {
    guideLink.href =
      "vi" === lang
        ? "https://github.com/duckmartians/Auto-Flow/blob/main/README_vi.md"
        : "https://github.com/duckmartians/Auto-Flow/blob/main/README.md";
  }
}

document.addEventListener("DOMContentLoaded", () => {
  const selector = document.getElementById("languageSelector");

  chrome.storage.local.get(["language"], (saved) => {
    const lang = saved.language || "en";
    if (selector.querySelector(`option[value="${lang}"]`)) {
      selector.value = lang;
      applyLanguage(lang);
    } else {
      selector.value = "en";
      applyLanguage("en");
    }
  });

  selector.addEventListener("change", (e) => {
    const lang = e.target.value;
    applyLanguage(lang);
    chrome.storage.local.set({ language: lang });
  });

  // Collapsible sections
  document.querySelectorAll(".changelog-header.collapsible").forEach((header) => {
    header.addEventListener("click", () => {
      const targetId = header.getAttribute("data-toggle");
      const body = document.getElementById(targetId);
      if (!body) return;
      header.classList.toggle("collapsed");
      body.classList.toggle("collapsed");
    });
  });

  document.getElementById("btn-glabs").addEventListener("click", () => {
    window.open(
      "https://github.com/duckmartians/G-Labs-Automation",
      "_blank",
    );
  });

  document.getElementById("btn-classic").addEventListener("click", () => {
    window.location.href = "sidepanel.html";
  });
});
